baseURL = "www.spo.hn"
languageCode = 'en-us'
title = 'Corey Spohn'
theme = ["PaperMod"]

mainSections = ["posts", "projects"]

# Creating the menu
[menu]

[[menu.main]]
identifier = "home"
name = "Home"
url = "/"
weight = 10

[[menu.main]]
identifier = "about"
name = "About"
url = "/about/"
weight = 20

[[menu.main]]
identifier = "posts"
name = "Posts"
url = "/posts/"
weight = 30

[[menu.main]]
identifier = "projects"
name = "Projects"
url = "/projects/"
weight = 40

[[menu.main]]
identifier = "publications"
name = "Publications"
url = "/publications/"
weight = 50

[[menu.main]]
identifier = "contact"
name = "Contact"
url = "/contact/"
weight = 60

# Parameters of the home page
[params]
[params.homeInfoParams]
# Title = "Corey Spohn"
Content = "I'm an astronomer/engineer who writes a lot of code to simulate exoplanet missions."

[[params.socialIcons]]
name = "GitHub"
url = "https://github.com/CoreySpohn/"
icon = "github"
