baseURL = "www.spo.hn"
languageCode = 'en-us'
title = 'Corey Spohn'
theme = ["PaperMod"]

mainSections = ["projects", "posts"]

# Creating the menu
[menu]

[[menu.main]]
identifier = "home"
name = "Home"
url = "/"
weight = 10

[[menu.main]]
identifier = "projects"
name = "Projects"
url = "/projects/"
weight = 20

[[menu.main]]
identifier = "publications"
name = "Publications"
url = "/publications/"
weight = 30

[[menu.main]]
identifier = "posts"
name = "Posts"
url = "/posts/"
weight = 40

[[menu.main]]
identifier = "about"
name = "About"
url = "/about/"
weight = 50

[[menu.main]]
identifier = "contact"
name = "Contact"
url = "/contact/"
weight = 60

# Parameters of the home page
[params]
ShowCodeCopyButtons = true

[params.homeInfoParams]
# Title = "Corey Spohn"
Content = "I'm an astronomer/engineer who writes a lot of code to simulate direct imaging exoplanet missions."

[[params.socialIcons]]
name = "GitHub"
url = "https://github.com/CoreySpohn/"
icon = "github"

# Python code highlighting
[params.assets]
disableHLJS = true

[markup.highlight]
codeFences = true
guessSyntax = true
lineNos = true
# noClasses = false
style = "gruvbox"

# pygmentsStyle = "gruvbox"
# pygmentsUseClasses = true

[module]
# Use mounts to exclude non-data files (e.g., README.md) from the data tree,
# while still exposing the YAML under data/dotme/data at the expected path.
[[module.mounts]]
source = "data"
target = "data"
excludeFiles = ["dotme/README.md"]
