# Name of the workflow
name: Build and Deploy Quarto Project

# Controls when the workflow will run
on:
  # Allows manual triggering from the Actions tab
  workflow_dispatch:
  # Triggers the workflow on push events to the main branch
  push:
    branches:
      - main

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build-and-deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Grant write permissions to the GITHUB_TOKEN to allow deployment to gh-pages
    permissions:
      contents: write

    steps:
      # 1. Check out the repository code
      - name: Check out repository
        uses: actions/checkout@v4

      # 2. Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          
      - name: Install Python dependencies
        run: |
          pip install pyyaml

      # 3. Set up Quarto CLI
      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          # Use a version compatible with awesomecv-typst
          version: '1.7.31'

      # 4. Install Typst compiler (essential for PDF generation)
      - name: Install Typst
        uses: typst-community/setup-typst@v3
        with:
          version: 'latest'

      # 5. Render all project outputs
      - name: Render Website
        run: quarto render --output-dir docs

      - name: Render Comprehensive CV
        run: |
          quarto render cv.qmd
          mkdir -p docs/cv
          mv cv.pdf docs/cv/cv.pdf

      - name: Render Research Resume
        run: |
          quarto render --profile research
          mv John_Doe_Resume_Research.pdf docs/cv/

      - name: Render Aerospace Resume
        run: |
          quarto render --profile aerospace
          mv John_Doe_Resume_Aerospace.pdf docs/cv/
        
      - name: Render Data Science Resume
        run: |
          quarto render --profile datascience
          mv John_Doe_Resume_DataScience.pdf docs/cv/

      # 6. Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
          # Use a custom commit message
          commit_message: "Deploy: ${{ github.event.head_commit.message }}"